/*
 * Generates `lib/styles/themeDefaults.scss`: every theme CSS variable at its default
 * value, so they already have values when the page first renders, before
 * `Vue.use(KThemePlugin)` has run. Run by `pregenerate.js`.
 */

const fs = require('node:fs');
const path = require('node:path');

const consola = require('consola');

// these are ES modules, loaded through Node's `require(esm)` support
const materialColors = require('../lib/styles/colorsMaterial').default;
const { defaultBrandColors, defaultTokenMapping } = require('../lib/styles/colorsDefault');
const { flattenThemeTree } = require('../lib/utils/themeCssVariableNaming');

const OUTPUT_PATH = path.resolve('./lib/styles/themeDefaults.scss');

// the tree `tokenMapping` paths are resolved against, as `theme.js` resolves them
const colors = { palette: materialColors, brand: defaultBrandColors };

let cachedValues = null;

/**
 * The color a `tokenMapping` entry points at, or `null` when it does not resolve.
 * Mirrors `generateTokenToColorMapping` in `lib/styles/theme.js`, which walks the
 * same dot path and treats a value without one as a literal color.
 */
function resolveToken(mapString) {
  if (!mapString.includes('.')) {
    return mapString;
  }
  let value = colors;
  for (const key of mapString.split('.')) {
    if (!value[key]) {
      return null;
    }
    value = value[key];
  }
  return typeof value === 'string' ? value : null;
}

/** Every theme CSS variable name mapped to the color it is emitted with. */
function getThemeCssVariableValues() {
  if (cachedValues) {
    return cachedValues;
  }
  const values = new Map([
    ...flattenThemeTree('palette', materialColors),
    ...flattenThemeTree('brand', defaultBrandColors),
  ]);
  for (const [name, mapString] of flattenThemeTree('tokens', defaultTokenMapping)) {
    const value = resolveToken(mapString);
    if (value) {
      values.set(name, value);
    }
  }
  cachedValues = values;
  return cachedValues;
}

const HEADER = `// Auto-generated by utils/extractThemeDefaults.js. Regenerate with \`yarn pregenerate\`.
// Defines every theme CSS variable at its default value, so they already have values
// when the page first renders, before \`Vue.use(KThemePlugin)\` has run.
`;

/** The `:root` rule defining every theme CSS variable at its default value. */
function themeDefaultsScss() {
  const declarations = [...getThemeCssVariableValues()].map(
    ([name, value]) => `  ${name}: ${value.toLowerCase()};`,
  );
  return `${HEADER}\n:root {\n${declarations.join('\n')}\n}\n`;
}

function writeThemeDefaults() {
  fs.writeFileSync(OUTPUT_PATH, themeDefaultsScss());
  consola.info(`Wrote theme defaults to ${OUTPUT_PATH}`);
}

exports.getThemeCssVariableValues = getThemeCssVariableValues;
exports.themeDefaultsScss = themeDefaultsScss;
exports.writeThemeDefaults = writeThemeDefaults;
