name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 10.x

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - run: yarn --frozen-lockfile

      - name: Pre-generate docs
        run: yarn run pregenerate

      - name: Run linter
        run: yarn run lint

      - name: Check for modified files
        run: |
          if [[ `git status --porcelain --untracked-files=no` ]]; then
            echo "Tracked files were modified by 'yarn run pregenerate'"
            exit 1
          else
            exit 0
          fi
