name: Update KDS Roadmap project statuses on Release

on:
  release:
    types: [published]

jobs:
  update-issues-statuses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: '20'

      - uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          app-id: ${{ secrets.LE_BOT_APP_ID }}
          private-key: ${{ secrets.LE_BOT_PRIVATE_KEY }}

      - name: Update Issues statuses
        uses: actions/github-script@v9
        env:
          KDS_ROADMAP_PROJECT_NUMBER: ${{ secrets.KDS_ROADMAP_PROJECT_NUMBER }}
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const { updateReleasedItemsStatuses } = require('./.github/githubUtils.js');
            const projectNumber = process.env.KDS_ROADMAP_PROJECT_NUMBER;
            updateReleasedItemsStatuses({context, github, projectNumber});