<template>

  <div :id="id" ref="tooltip" class="ui-tooltip" role="tooltip">
    <slot></slot>
  </div>

</template>


<script>

  import UUID from './helpers/uuid';

  // check for Nuxt.js SSR
  const nuxtServerSideRendering = process && process.server;
  let Tooltip = undefined;
  if (!nuxtServerSideRendering) {
    Tooltip = require('tether-tooltip');
  }

  export default {
    name: 'KeenUiTooltip',

    props: {
      trigger: {
        type: String,
        required: true,
      },
      position: {
        type: String,
        default: 'bottom center',
      },
      openOn: {
        type: String,
        default: 'hover focus',
      },
      openDelay: {
        type: Number,
        default: 0,
      },
    },

    data() {
      return {
        tooltip: null,
        id: UUID.short('ui-tooltip-'),
      };
    },

    watch: {
      trigger() {
        if (this.tooltip === null) {
          this.initialize();
        }
      },
    },

    mounted() {
      if (this.tooltip === null) {
        this.initialize();
      }
    },

    beforeDestroy() {
      if (this.tooltip !== null) {
        this.tooltip.destroy();
      }
    },

    methods: {
      initialize() {
        if (process && process.client) {
          if (this.trigger !== undefined && this.$parent.$refs[this.trigger]) {
            const triggerEl = this.$parent.$refs[this.trigger]._isVue
              ? this.$parent.$refs[this.trigger].$el // Use .$el if the ref is a Vue component
              : this.$parent.$refs[this.trigger];

            this.tooltip = new Tooltip({
              target: triggerEl,
              content: this.$refs.tooltip,
              classes: 'ui-tooltip--theme-default',
              position: this.position,
              openOn: this.openOn,
              openDelay: this.openDelay,
            });

            triggerEl.setAttribute('aria-describedby', this.id);
          }
        }
      },
    },
  };

</script>


<style lang="scss">

  @import './styles/imports';

  /* stylelint-disable */

  $tooltip-content-margin: rem-calc(4px) !default;

  .ui-tooltip {
    line-height: 1;
  }

  // The following classes are unprefixed and not BEM
  // because they are generated by Tether Tooltip

  .tooltip-element,
  .tooltip-element::after,
  .tooltip-element::before,
  .tooltip-element *,
  .tooltip-element *::after,
  .tooltip-element *::before {
    box-sizing: border-box;
  }

  .tooltip-element {
    position: absolute;
    display: none;
    opacity: 0;
    transition: opacity 0.2s;
  }

  .tooltip-element.tooltip-open {
    display: block;
  }

  .tooltip-element.tooltip-after-open {
    opacity: 1;
  }

  .tooltip-element.ui-tooltip--theme-default {
    z-index: $z-index-tooltip;
    max-width: 100%;
    max-height: 100%;
    pointer-events: none;

    .tooltip-content {
      position: relative;
      display: flex;
      align-items: center;
      height: rem-calc(26px);
      padding: rem-calc(0 8px);
      font-family: inherit;
      font-size: rem-calc(13px);
      line-height: 1;
      color: white;
      background: $md-grey-900;
      border-radius: $ui-default-border-radius;
      opacity: 0.9;
    }

    &.tooltip-element-attached-bottom.tooltip-element-attached-center .tooltip-content {
      margin-bottom: $tooltip-content-margin;
    }

    &.tooltip-element-attached-top.tooltip-element-attached-center .tooltip-content {
      margin-top: $tooltip-content-margin;
    }

    &.tooltip-element-attached-right.tooltip-element-attached-middle .tooltip-content {
      margin-right: $tooltip-content-margin;
    }

    &.tooltip-element-attached-left.tooltip-element-attached-middle .tooltip-content {
      margin-left: $tooltip-content-margin;
    }

    &.tooltip-element-attached-top.tooltip-element-attached-left.tooltip-target-attached-bottom
      .tooltip-content {
      margin-top: $tooltip-content-margin;
    }

    &.tooltip-element-attached-top.tooltip-element-attached-right.tooltip-target-attached-bottom
      .tooltip-content {
      margin-top: $tooltip-content-margin;
    }

    &.tooltip-element-attached-bottom.tooltip-element-attached-left.tooltip-target-attached-top
      .tooltip-content {
      margin-bottom: $tooltip-content-margin;
    }

    &.tooltip-element-attached-bottom.tooltip-element-attached-right.tooltip-target-attached-top
      .tooltip-content {
      margin-bottom: $tooltip-content-margin;
    }

    &.tooltip-element-attached-top.tooltip-element-attached-right.tooltip-target-attached-left
      .tooltip-content {
      margin-right: $tooltip-content-margin;
    }

    &.tooltip-element-attached-top.tooltip-element-attached-left.tooltip-target-attached-right
      .tooltip-content {
      margin-left: $tooltip-content-margin;
    }

    &.tooltip-element-attached-bottom.tooltip-element-attached-right.tooltip-target-attached-left
      .tooltip-content {
      margin-right: $tooltip-content-margin;
    }

    &.tooltip-element-attached-bottom.tooltip-element-attached-left.tooltip-target-attached-right
      .tooltip-content {
      margin-left: $tooltip-content-margin;
    }
  }

</style>
